Repository kognise/water.css, pull requests merged in 2020-05, with the labels that each got.

#192 Add Print Stylesheet
  src/parts/_core.css
  src/parts/_print.css
Labels: bug

#191 [WIP] New File Structure + Version Picker
  .eslintrc.json
  .prettierignore
  README.md
  docs/index.html
  docs/script.js
  docs/style.css
  docs/versionpicker.html
  gulpfile.js
  package.json
  src/builds/dark-legacy.css
  src/builds/dark-legacy.standalone.css
  src/builds/dark.css
  src/builds/dark.standalone.css
  src/builds/light-legacy.css
  src/builds/light-legacy.standalone.css
  src/builds/light.css
  src/builds/light.standalone.css
  src/builds/water.css
  src/parts/_forms.css
Labels: enhancement, wip

#196 README updates
  README.md
Labels: enhancement

#199 Add pa11y and fix accessibility issues
  .huskyrc.json
  accessibility.js
  docs/index.html
  package.json
  src/variables-dark.css
  src/variables-light.css
  yarn.lock
Labels: accessibility
